### ISSUE TITLE
Can't get it to work on iOS and Android

### ISSUE THREAD

**Issue by derkweijers** [CometTools/wake_on_lan#1]
Fist of all; thanks for taking the time to create this package. Really appreciate it!

I'm, however, pulling my hair out to get it to work. I have the following widget

```dart
import 'package:flutter/material.dart';
import 'package:lanwake/screens/EntryScreen.dart';
import 'package:wake_on_lan/wake_on_lan.dart';
import '../models/Device.dart';

class DeviceCard extends StatelessWidget {
  final VoidCallback changedCallback;
  final Device device;

  DeviceCard({
    @required this.changedCallback,
    @required this.device,
  });

  _sendThePackage() async {
    // Mac is a valid address, checked with the helper from this package
    MACAddress macAddress = MACAddress.from(this.device.mac);
   // IP is a valid address, checked with the helper from this package
    IPv4Address ipv4Address = IPv4Address.from(this.device.ip);
    await WakeOnLAN.from(ipv4Address, macAddress, port: this.device.port).wake();
    print('Sent');
  }

  @override
  Widget build(BuildContext context) {
    return Card(
      child: Column(
        children: [
          ListTile(
            title: Text(this.device.name),
            subtitle: Text(this.device.ip),
          ),
          Row(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              ElevatedButton(
                child: Text('Wake!'),
                onPressed: () => _sendThePackage(),
              ),
            ],
          ),
        ],
      ),
    );
  }
}
```
I would say this should work. However, when pressing the button nothing happens. And for the life of me, I can't figure out why. I've tried running it from both simulators and building a release package for Androind and installing it on a physical device.

Any help would be appreciated. Thanks!

**Comment by JagandeepBrar** [comment]
Have you ensured that the IP address is correct and that the MAC address of the machine is correct?

The way that you are running it is correct, and just tested in a quick test script and it seems to still be working correctly.

Also it appears you are using Flutter, which branch of Flutter are you currently using?

**Comment by derkweijers** [comment]
Thank you for the reply. It's flutter indeed, current branch (1.22.2).

> Remember that the IP address should be the broadcast address for your network, which can vary by subnets but on a conventional home network of 192.168.0.0/24, the broadcast address is 192.168.0.255. You can use this tool to confirm your broadcast address: http://jodies.de/ipcalc

This did the trick! Need to read into the WoL specs a bit more I'm afraid.
